services:
  
  organizr:
    image: ghcr.io/organizr/organizr
    container_name: organizr
    restart: unless-stopped
    ports:
      - "8200:80"          
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid  
    volumes:
      - ./data:/config

      


